version: '2'
services:
  front:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www:ro
      - ./docker/front/symfony.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./docker/front/minimal.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

  engine:
    build: ./docker/engine/
    expose:
        - "9000"
        - "9001"
    ports:
        - "9001:9001"
    environment:
        PHP_XDEBUG_ENABLED: 1
        XDEBUG_CONFIG: remote_host=172.19.0.1
        SERVER_NAME: docker
    links:
      - chrometesting
      - firefoxtesting
    volumes:
      - .:/var/www:rw
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: /var/www
    networks:
      - default
    dns_search:
      - engine

  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
      - MYSQL_DATABASE=user_password
    volumes:
      - db:/var/lib/mysql:rw
    networks:
      - default
    dns_search:
      - db

  hubtesting:
    image: selenium/hub:3.7.0
    ports:
      - 4444:4444

  chrometesting:
    image: selenium/node-chrome-debug:3.7.0
    ports:
      # Port is used for VNC only
      - 5900:5900
    links:
      - hubtesting:hub
    external_links:
      - reverseproxy:fft-selenium.dev.zol.fr

  firefoxtesting:
    image: selenium/node-firefox-debug:3.7.0
    ports:
      # Port is used for VNC only
      - 5901:5900
    links:
      - hubtesting:hub
    external_links:
      - reverseproxy:fft-selenium.dev.zol.fr

volumes:
  db: {}
networks:
  default: {}
